amcl:
  ros__parameters:
    use_sim_time: false
    alpha1: 1.0
    alpha2: 1.0
    alpha3: 1.0
    alpha4: 1.0
    alpha5: 1.0
    base_frame_id: "base_footprint"
    beam_skip_distance: 0.5
    beam_skip_error_threshold: 0.9
    beam_skip_threshold: 0.3
    do_beamskip: false
    global_frame_id: "map"
    lambda_short: 0.1
    laser_likelihood_max_dist: 2.0
    laser_max_range: -1.0
    laser_min_range: -1.0
    laser_model_type: "likelihood_field"
    max_beams: 60
    max_particles: 2000
    min_particles: 500
    odom_frame_id: "odom"
    pf_err: 0.05
    pf_z: 0.99
    recovery_alpha_fast: 0.0
    recovery_alpha_slow: 0.0
    resample_interval: 1
    robot_model_type: "differential"
    save_pose_rate: 0.5
    sigma_hit: 0.2
    tf_broadcast: true
    transform_tolerance: 1.5
    update_min_a: 0.1
    update_min_d: 0.1
    z_hit: 0.5
    z_max: 0.05
    z_rand: 0.5
    z_short: 0.05
    use_map_topic_: false

amcl_map_client:
  ros__parameters:
    use_sim_time: false

amcl_rclcpp_node:
  ros__parameters:
    use_sim_time: false

bt_navigator:
  ros__parameters:
    use_sim_time: false
    bt_xml_filename: /home/snuc/ros2_ws/src/navigation2/nav2_bt_navigator/behavior_trees/navigate_w_replanning_and_recovery.xml
    #/home/snuc/ros2_ws/src/navigation2/nav2_bt_navigator/behavior_trees/navigate_w_replanning.xml
#"bt_navigator.xml"
# 'navigate_w_recovery_retry.xml'

dwb_controller:
  ros__parameters:
    use_sim_time: false
    debug_trajectory_details: True
    min_vel_x: 0.0
    min_vel_y: 0.0
    max_vel_x: 0.3
    max_vel_y: 0.0
    max_vel_theta: 1.5
    min_speed_xy: 1.0
    max_speed_xy: 3.0
    min_speed_theta: 0.3
    min_x_velocity_threshold: 0.001
    # Add high threshold velocity for turtlebot 3 issue.
    # https://github.com/ROBOTIS-GIT/turtlebot3_simulations/issues/75
    min_y_velocity_threshold: 0.02
    min_theta_velocity_threshold: 0.001
    acc_lim_x: 2.5
    acc_lim_y: 0.0
    acc_lim_theta: 3.2
    decel_lim_x: -2.5
    decel_lim_y: 0.0
    decel_lim_theta: -3.2
    vx_samples: 20
    vy_samples: 5
    vtheta_samples: 20
    sim_time: 1.0
    linear_granularity: 0.05
    xy_goal_tolerance: 0.08
    # critics: ["RotateToGoal", "Oscillation", "BaseObstacle", "GoalAlign", "PathAlign", "PathDist", "GoalDist"]
    critics: ["RotateToGoal", "Oscillation", "GoalAlign", "PathAlign", "PathDist", "GoalDist"]
    BaseObstacle.scale: 0.02
    PathAlign.scale: 32.0
    GoalAlign.scale: 24.0
    PathDist.scale: 128.0
    GoalDist.scale: 24.0
    RotateToGoal.scale: 32.0

global_costmap:
  world_model:
    ros__parameters:
      transform_tolerance: 1.0
      static_layer.first_map_from_service: true
      always_send_full_costmap: true
      use_sim_time: false
      robot_radius: 0.17
      obstacle_layer:
        enabled: True
      observation_sources: scan
      scan:
        topic: /scan
        max_obstacle_height: 2.0
        clearing: True
        marking: True


local_costmap:
  dwb_controller:
    ros__parameters:
      plugin_names: ["obstacle_layer", "inflation_layer"]
      plugin_types: ["nav2_costmap_2d::ObstacleLayer", "nav2_costmap_2d::InflationLayer"]
      global_frame: map
      always_send_full_costmap: true
      use_sim_time: false
      rolling_window: true
      robot_radius: 0.17
      inflation_layer:
        cost_scaling_factor: 3.0
      obstacle_layer:
        enabled: True
      observation_sources: scan
      static_layer:
        enabled: False
      scan:
        topic: /scan
        max_obstacle_height: 2.0
        clearing: True
        marking: True

map_server:
  ros__parameters:
    mode: scale
    use_sim_time: false
    yaml_filename: "/home/snuc/ros2_ws/src/openrover/openrover_demo/maps/map.yaml"

lifecycle_manager:
  ros__parameters:
    use_sim_time: false
    autostart: true

lifecycle_manager_service_client:
  ros__parameters:
    use_sim_time: false

lifecycle_manager_client_service_client:
  ros__parameters:
    use_sim_time: false

navfn_planner:
  ros__parameters:
    use_sim_time: false
    tolerance: 0.0
    use_astar: false

navfn_planner_GetCostmap_client:
  ros__parameters:
    use_sim_time: false

robot_state_publisher:
  ros__parameters:
    use_sim_time: false

world_model:
  ros__parameters:
    use_sim_time: false
